name: Build TWRP recovery - Test

on:
  workflow_dispatch:

env:
  MANIFEST: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp
  MANIFEST_BRANCH: twrp-11
  DEVICE: spes
  DT_LINK: https://github.com/shashankx86/android_device_xiaomi_spes-TWRP
  DT_PATH: device/xiaomi/spes
  TARGET: bootimage
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
            
       - name: Sync recovery source and device tree
         run: |
             mkdir work
             cd work
             sudo apt update && sudo apt install tmate
             
       - name: Sync recovery source and device tree1
         run: |
             wget https://raw.githubusercontent.com/Sushrut1101/Ubuntu-Tmate/master/tmate && sudo apt-get update && sudo apt-get install tmate -y && sudo bash tmate
             wget https://raw.githubusercontent.com/Sushrut1101/Ubuntu-Tmate/master/spam.sh && sh spam.sh
