name: Build TWRP recovery - Test

on:
  workflow_dispatch:

env:
  MANIFEST: https://github.com/minimal-manifest-twrp/platform_manifest_twrp_aosp
  MANIFEST_BRANCH: twrp-11
  DEVICE: spes
  DT_LINK: https://github.com/shashankx86/android_device_xiaomi_spes-TWRP
  DT_PATH: device/xiaomi/spes
  TARGET: bootimage
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
            
       - name: Generate Tmate Session
         run: |
          sudo bash tmate.sh | tee /tmp/ssh.txt
          cat /tmp/ssh.txt
       - name: Ignore this
         run: |
          while true; do sleep 1; done
