name: Build TWRP recovery - Test

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
            
       - name: Generate Tmate Session
         run: |
          sudo bash tmate.sh | tee /tmp/ssh.txt
          cat /tmp/ssh.txt
       - name: Ignore this
         run: |
          while true; do sleep 1; done
