name: Ubuntu

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  ubuntu:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Generate Tmate Session
        run: |
          sudo apt install tmate 
          git clone https://github.com/Sushrut1101/MultiLinux-SSH 1
          cd 1
          sudo bash tmate.sh | tee /tmp/ssh.txt
          cat /tmp/ssh.txt

      - name: Ignore this
        run: |
          while true; do sleep 1; done
